//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINESTOCKtbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINESTOCKtbl()
        {
            this.REMINDERDETAILStbl = new HashSet<REMINDERDETAILStbl>();
        }
    
        public short ID { get; set; }
        public Nullable<short> IDMEDICINE { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
    
        public virtual MEDICINEtbl MEDICINEtbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMINDERDETAILStbl> REMINDERDETAILStbl { get; set; }
    }
}
