//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDERDETAILStbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REMINDERDETAILStbl()
        {
            this.REMINDERStbl = new HashSet<REMINDERStbl>();
        }
    
        public short ID { get; set; }
        public Nullable<short> IDMEDICINESTOCK { get; set; }
        public string SUBJECTGMAIL { get; set; }
        public string COMMENT { get; set; }
        public Nullable<short> AMOUNTDAYS { get; set; }
        public Nullable<short> FREQUINCY { get; set; }
        public string DOSAGE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<bool> STATUSMEDICINE { get; set; }
    
        public virtual MEDICINESTOCKtbl MEDICINESTOCKtbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMINDERStbl> REMINDERStbl { get; set; }
    }
}
