//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDERStbl
    {
        public short ID { get; set; }
        public Nullable<short> IDDETAIL { get; set; }
        public Nullable<System.DateTime> DATETAKE { get; set; }
        public Nullable<System.DateTime> HOURTAKE { get; set; }
    
        public virtual REMINDERDETAILStbl REMINDERDETAILStbl { get; set; }
    }
}
